### ISSUE TITLE
Request for cooperation: bash-modules

### ISSUE THREAD

**Issue by vlisivka** [dnmfarrell/jp#5]
I'm working on bash-modules project. I'm about to release version 4.0.

As a bash scripter, can you provide me with feedback about style and usability of bash-modules, please?

See https://github.com/vlisivka/bash-modules .

**Comment by dnmfarrell** [comment]
For feedback on code, I'd reach out to relevant communities like [/r/bash](https://www.reddit.com/r/bash/).
